# paths (to the bam files) can be absolute or relative
bam_files:
  - data/bams/A.bam
  - data/bams/B.bam
  - bams/C.bam

# percentage of reads to keep
proportion_reads_to_keep:
  - 0.2
  - 0.5
  - 0.7

reference_genome: data/genome.fa
